# -*- coding: utf-8 -*-
"""Tugas Pertemuan 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15k6MxbAa0MIdbr2lPb_lgBKSWcHJNmo9

"""Mencari kpk 3 dan 4""

def cari_kpk(a, b):
    kelipatan = max(a, b)
    while True:
        if kelipatan % a == 0 and kelipatan % b == 0:
            return kelipatan
        kelipatan += 1

# Main Program
a = 3
b = 4
kpk = cari_kpk(a, b)
print("KPK dari", a, "dan", b, "adalah", kpk)

"""Fungsi untuk menukar posisi dua variabel x dan y"""

def tukar_buah(piring1, piring2):
    # Gunakan piring3 sebagai tempat sementara
    piring3 = piring1    # Letakkan manggis (piring1) di piring3
    piring1 = piring2    # Letakkan pisang (piring2) di piring1
    piring2 = piring3    # Letakkan manggis (piring3) di piring2
    return piring1, piring2

# Main Program
piring1 = "Manggis"
piring2 = "Pisang"

piring1, piring2 = tukar_buah(piring1, piring2)
print("Piring 1 sekarang berisi:", piring1)
print("Piring 2 sekarang berisi:", piring2)

"""Hitung luas dari segitiga"""

def hitung_luas_segitiga():
    # Inisialisasi variabel
    alas = 25
    tinggi = 30

    # Hitung luas segitiga
    luas = 0.5 * alas * tinggi

    # Tampilkan hasil
    print("Luas segitiga adalah:", luas)

# Memanggil fungsi untuk menghitung luas segitiga
hitung_luas_segitiga()

"""luas jajar genjang"""

def hitung_luas_jajar_genjang():
    # Inisialisasi variabel
    panjang = 5
    tinggi = 3

    # Hitung luas jajar genjang
    luas = panjang * tinggi

    # Tampilkan hasil
    print("Luas jajar genjang adalah:", luas)

# Memanggil fungsi untuk menghitung luas jajar genjang
hitung_luas_jajar_genjang()

"""volume tabung (jari-jari = 3, tinggi = 5)


"""

def hitung_volume_tabung():
    # Inisialisasi variabel
    jari_jari = 3
    tinggi = 5
    pi = 3.14159  # Menggunakan nilai pi secara manual

    # Hitung volume tabung
    volume = pi * jari_jari**2 * tinggi

    # Tampilkan hasil
    print("Volume tabung adalah:", volume)

# Memanggil fungsi untuk menghitung volume tabung
hitung_volume_tabung()

"""Volume kerucut"""

def hitung_volume_kerucut():
    # Inisialisasi variabel
    diameter = 5
    tinggi = 4
    pi = 3.14159  # Pi manual

    # Hitung jari-jari
    jari_jari = diameter / 2

    # Hitung volume kerucut
    volume = (1/3) * pi * jari_jari**2 * tinggi

    # Tampilkan hasil
    print("Volume kerucut adalah:", volume)

# Memanggil fungsi untuk menghitung volume kerucut
hitung_volume_kerucut()
