# -*- coding: utf-8 -*-
"""1. Cari nilai KPK dari 3 dan 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15k6MxbAa0MIdbr2lPb_lgBKSWcHJNmo9
"""

def cari_kpk(a, b):
    kelipatan = max(a, b)
    while True:
        if kelipatan % a == 0 and kelipatan % b == 0:
            return kelipatan
        kelipatan += 1

# Main Program
a = 3
b = 4
kpk = cari_kpk(a, b)
print("KPK dari", a, "dan", b, "adalah", kpk)